Repository FantasyFrontiers/FantasyFrontiers, pull requests merged in 2023-10, with the labels that each got.

#2 Create FUNDING.yml
  .github/FUNDING.yml
Labels: hacktoberfest

#24 Select start skill
  .github/workflows/gradle.yml
  build.gradle.kts
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/data/model/player/Character.kt
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/data/model/player/Skill.kt
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/data/model/player/Skills.kt
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/listeners/setup/CharacterSetup.kt
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/utils/extensions/MathExtensions.kt
  src/main/resources/translations/en-US.json
  src/test/kotlin/de/coasterfreak/fantasyfrontiers/data/model/player/SkillTest.kt
Labels: enhancement

#36 33 🍃Sentry
  build.gradle.kts
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/Start.kt
Labels: enhancement, hacktoberfest

#46 Documentation notice
  README.md
Labels: documentation, chore

#45 feat : Item class implementation #40
  src/main/kotlin/de/coasterfreak/fantasyfrontiers/data/model/items/Item.kt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#49 Structure Imports
  build.gradle.kts
Labels: documentation, hacktoberfest, chore

#53 Inventories and Item rework
  .github/workflows/gradle.yml
  src/main/kotlin/net/fantasyfrontiers/data/db/items/InventoriesTable.kt
  src/main/kotlin/net/fantasyfrontiers/data/db/player/CharacterTable.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/extras/Translatable.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/extras/TranslatableNameDesc.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/items/Inventory.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/items/Item.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/items/ItemStack.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/player/Character.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/town/Travel.kt
  src/main/kotlin/net/fantasyfrontiers/utils/DatabaseConnection.kt
  src/main/resources/translations/en-US.json
  src/test/kotlin/net/fantasyfrontiers/data/db/items/InventoriesTableKtTest.kt
  src/test/kotlin/net/fantasyfrontiers/data/model/items/ItemStackTest.kt
Labels: enhancement, chore

#60 InventoryDisplay
  src/main/kotlin/net/fantasyfrontiers/data/model/items/Inventory.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/items/Item.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/items/ItemStack.kt
  src/main/kotlin/net/fantasyfrontiers/data/model/town/Travel.kt
  src/main/kotlin/net/fantasyfrontiers/listeners/game/anytime/BackpackCommand.kt
  src/main/kotlin/net/fantasyfrontiers/listeners/setup/SystemAnnouncementSetup.kt
  src/main/kotlin/net/fantasyfrontiers/utils/functions/DiscordFunctions.kt
  src/main/resources/translations/en-US.json
  src/test/kotlin/net/fantasyfrontiers/data/model/items/InventoryTest.kt
Labels: enhancement

#64 Add logback-classic as a logger implementation
  build.gradle.kts
  src/main/kotlin/net/fantasyfrontiers/manager/RegisterManager.kt
  src/main/kotlin/net/fantasyfrontiers/utils/SentryWrapperEventListener.kt
Labels: bug, hacktoberfest, chore
